handle no lables returned

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -2,7 +2,7 @@
 set -euo pipefail
 
 if [[ "${BUILDKITE_PIPELINE_PROVIDER:-}" != "github" ]] ; then
-  echo "⛔️ this plugin can only be used on piplines associated with github repositories" >&2
+  echo "⛔️  this plugin can only be used on piplines associated with github repositories" >&2
   exit 1
 fi
 
@@ -16,7 +16,7 @@ repoFq=""
 if [[ "${BUILDKITE_REPO:-}" =~ github.com[:/](.*).git[/]? ]]; then
   repoFq="${BASH_REMATCH[1]}"
 else
-  echo "⛔️ the BUILDKITE_REPO variable has an unexpected format" >&2
+  echo "⛔️  the BUILDKITE_REPO variable has an unexpected format" >&2
   exit 2
 fi
 
@@ -28,7 +28,7 @@ elif [[ -n "${BUILDKITE_PLUGIN_GITHUB_PR_LABELS_TOKEN_FROM_ENV:-}" ]]; then
   echo "~~~ 📋 reading github token from env var"
   githubToken="${!BUILDKITE_PLUGIN_GITHUB_PR_LABELS_TOKEN_FROM_ENV}"
 else
-  echo "⚠️ configuration is missing a valid 'token-from' stanza. requests to github will be unauthenticated"
+  echo "⚠️  configuration is missing a valid 'token-from' stanza. requests to github will be unauthenticated"
 fi
 
 echo "~~~ :github: retrieving pull-request labels"
@@ -39,7 +39,11 @@ else
   labels=$(curl -f -Ss -H @- "https://api.github.com/repos/${repoFq}/pulls/${pullReqNo}" <<<"Authorization: Bearer ${githubToken}" | jq -r "$jqFilter" -)
 fi
 
-echo "~~~ :github: labels for PR #${pullReqNo} are: ${labels}"
+if [[ -z "${labels}" ]]; then
+  echo "~~~ :github: PR #${pullReqNo} has no labels"
+else
+  echo "~~~ :github: PR #${pullReqNo} has the following labels: ${labels}"
+fi
 
 if [[ -n "${BUILDKITE_PLUGIN_GITHUB_PR_LABELS_PUBLISH_METADATA_KEY:-}" ]]; then
   metaDataKey="${BUILDKITE_PLUGIN_GITHUB_PR_LABELS_PUBLISH_METADATA_KEY}"
